version: '2'
services:
  hubot:
    container_name: hubot-rocketchat
    environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=botpassword
    - BOT_NAME=bot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    image: rocketchat/hubot-rocketchat
    ports:
    - 3001:8080
  mongo:
    command: mongod --smallfiles --oplogSize 128
    extends:
      file: ../database/mongo.yml
      service: mongo
  rocketchat:
    container_name: rocketchat
    environment:
      ROOT_URL: http://localhost:3000
    image: rocketchat/rocket.chat:0.14.0
    ports:
    - 3000:3000
    restart: always
