version: '2'
services:
  mysql:
    extends:
      file: ../database/mysql.yml
      service: mysql
  wordpress:
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: ${db_pass}
      WORDPRESS_DB_USER: root
    image: wordpress
    ports:
    - 80:80
    volumes:
    - ./wordpress_html:/var/www/html
