version: '2'
services:
  mongo:
    container_name: db
    extends:
      file: ../database/mongo.yml
      service: mongo
  redis:
    extends:
      file: ../database/redis.yml
      service: redis
  hublin:
    container_name: hublin
    image: linagora/hublin
    ports:
    - 8080:8080
