version: '2'
services:
  mysql:
    environment:
      MYSQL_DATABASE: openfire
      MYSQL_PASSWORD: ${usr_pass}
      MYSQL_USER: openfire
    extends:
      file: ../database/mysql.yml
      service: mysql
  openfire:
    container_name: openfire
    environment:
      DB_1_PORT_3306_TCP_ADDR: mysql
      DB_1_PORT_3306_TCP_PORT: 3306
      JDBC_PASSWORD: ${usr_pass}
      JDBC_USERNAME: openfire
    image: fanatic/openfire
    ports:
    - 9090:9090
    restart: always
    volumes:
    - ./openfire_data:/data/openfire
