version: '2'
services:
  mysql:
    environment:
      MYSQL_DATABASE: question2answer
      MYSQL_PASSWORD: ${usr_pass}
      MYSQL_USER: question2answer
    extends:
      file: ../db/mysql.yml
      service: mysql
  question2answer:
    container_name: question2answer
    environment:
      QUESTION2ANSWER_DB_USER: question2answer
      QUESTION2ANSWER_DB_PASSWORD: ${usr_pass}
      QUESTION2ANSWER_DB_NAME: question2answer
    image: wiesom/question2answer
    restart: always
    ports:
    - 80:80

