version: '2'
services:
  pentaho:
    container_name: pentaho
    environment:
      PGHOST: postgres
      PGPASSWORD: ${db_pass}
      PGUSER: postgres
    image: wmarinho/pentaho-biserver:5.1-TRUNK
    ports:
    - 8080:8080
  postgres:
    extends:
      file: ../db/postgres.yml
      service: postgres
