version: '2'
services:
  mysql:
    extends:
      file: ../db/mysql.yml
      service: mysql
    environment:
      MYSQL_DATABASE: spagobi
  spagoBI:
    container_name: spagoBI
    environment:
      DB_ENV_MYSQL_USER: root
      DB_ENV_MYSQL_PASSWORD: ${db_pass}
      DB_ENV_MYSQL_DATABASE: spagobi
      DB_PORT_3306_TCP_ADDR: mysql
      DB_PORT_3306_TCP_PORT: 3306
      WAIT_MYSQL: true
    image: spagobilabs/spagobi:latest
    ports:
    - 8080:8080
    restart: on-failure
    volumes:
    - ./spagoBI_data:/home/SpagoBI/database

