version: '2'
services:
  icecast:
    container_name: icecast
    environment:
    - ICECAST_SOURCE_PASSWORD: ${source_pass}
    - ICECAST_ADMIN_PASSWORD: ${admin_pass}
    - ICECAST_PASSWORD: ${icecast_pass}
    - ICECAST_RELAY_PASSWORD: ${icecast_relay_pass}
    image: moul/icecast
    ports:
    - 8000:8000
    volumes:
    - ./icecast_logs:/var/log/icecast2
    - ./icecast_localtime:/etc/localtime
